# Generated by Django 3.2.12 on 2023-07-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylist', '0001_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('ky_number', models.IntegerField()),
                ('tj_number', models.IntegerField()),
                ('list_number', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mylist.myfolder')),
                ('master_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.song')),
            ],
        ),
    ]
