# Generated by Django 4.2.2 on 2023-07-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='/home/jibeen/workspace/final_prj/Alsong-Dlsong/backend/static/img/user_default.png', upload_to='profile_img/'),
        ),
    ]
