# Generated by Django 3.1.1 on 2023-06-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0004_auto_20230616_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='mylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('ky_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_set', to='song.kysong')),
                ('tj_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_set', to='song.tjsong')),
            ],
        ),
    ]
