# Generated by Django 4.2.2 on 2023-07-03 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylist', '0001_initial'),
    ]

    operations = [
        
    ]
