# Generated by Django 4.2.2 on 2023-07-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_myfolder_user_mylist_user_alter_mylist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
