# Generated by Django 3.1.1 on 2023-06-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20230616_1219'),
        ('mylist', '0003_auto_20230616_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='ky_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_set', to='song.kysong'),
        ),
        migrations.AlterField(
            model_name='mylist',
            name='tj_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_set', to='song.tjsong'),
        ),
    ]
