# Generated by Django 3.1.1 on 2023-06-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('mylist', '0004_auto_20230616_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='listname',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mylist',
            name='list_name',
            field=models.CharField(default='노래', max_length=30),
        ),
        migrations.AddField(
            model_name='mylist',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mylist',
            name='user',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='myfolder',
            fields=[
                ('list_name', models.CharField(default='노래', max_length=30)),
                ('list_number', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylist.mylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='mylist',
            name='list_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mylist.myfolder'),
        ),
    ]
