# Generated by Django 3.1.1 on 2023-07-19 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mylist', '0004_myfolder_user_mylist_user'),
    ]

    operations = [
        
    ]
