# Generated by Django 4.2.2 on 2023-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_auto_20230617_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
