# Generated by Django 3.1.1 on 2023-06-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0005_auto_20230617_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfolder',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
