# Generated by Django 3.1.1 on 2023-06-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_alter_mylist_id'),
        ('mylist', '0006_auto_20230623_1014'),
    ]

    operations = [
    ]
