# Generated by Django 3.1.1 on 2023-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kysong',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('song_num', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
    ]
