# Generated by Django 3.1.1 on 2023-07-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ky_pop',
            fields=[
                ('rank', models.IntegerField()),
                ('title', models.TextField(max_length=255)),
                ('artist', models.TextField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('song_num_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kysong',
            fields=[
                ('song_num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('master_title', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('master_singer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('play', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, default='none', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tj_pop',
            fields=[
                ('rank', models.IntegerField()),
                ('title', models.TextField(max_length=255)),
                ('artist', models.TextField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('song_num_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tjsong',
            fields=[
                ('song_num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('master_title', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('master_singer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('play', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('genre', models.CharField(blank=True, default='none', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('cmp', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('master_title', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('master_singer', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('play', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('제목_KY', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('가수_KY', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('melon_tj', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('genre', models.TextField(blank=True, default='none', max_length=255, null=True)),
                ('master_number', models.IntegerField(primary_key=True, serialize=False)),
                ('ky_song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.kysong')),
                ('tj_song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.tjsong')),
            ],
        ),
    ]
