# Generated by Django 4.2.2 on 2023-07-12 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kysong',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('song_num', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, default='none', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tjsong',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('key', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('song_num', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(blank=True, default='none', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tj_pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(max_length=30, null=True)),
                ('writer', models.CharField(max_length=30, null=True)),
                ('song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tjpop_set', to='song.tjsong')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('ky_song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.kysong')),
                ('tj_song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.tjsong')),
            ],
        ),
        migrations.CreateModel(
            name='Ky_pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(max_length=30, null=True)),
                ('writer', models.CharField(max_length=30, null=True)),
                ('song_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kypop_set', to='song.kysong')),
            ],
        ),
    ]
