# Generated by Django 3.1.1 on 2023-06-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ky_pop',
            old_name='ky_number',
            new_name='song_num',
        ),
        migrations.RenameField(
            model_name='tj_pop',
            old_name='tj_number',
            new_name='song_num',
        ),
        migrations.AlterField(
            model_name='ky_pop',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ky_pop',
            name='cmp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ky_pop',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tj_pop',
            name='artist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tj_pop',
            name='cmp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tj_pop',
            name='writer',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
