# Generated by Django 3.1.1 on 2023-06-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_tjsong'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cmp', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('ky_song_num', models.IntegerField(max_length=20)),
                ('tj_song_num', models.IntegerField(max_length=20)),
            ],
        ),
    ]
