# Generated by Django 3.1.1 on 2023-06-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysong',
            name='cmp',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kysong',
            name='genre',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kysong',
            name='key',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kysong',
            name='writer',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cmp',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='ky_song_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.kysong'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tj_song_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.tjsong'),
        ),
        migrations.AlterField(
            model_name='song',
            name='writer',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tjsong',
            name='cmp',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tjsong',
            name='genre',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tjsong',
            name='key',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tjsong',
            name='writer',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
