# Generated by Django 3.1.1 on 2023-06-16 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20230616_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysong',
            name='song_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='ky_song_num',
            field=models.ForeignKey(db_column='ky_num', on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.kysong'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tj_song_num',
            field=models.ForeignKey(db_column='tj_num', on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.tjsong'),
        ),
        migrations.AlterField(
            model_name='tjsong',
            name='song_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
