# Generated by Django 3.1.1 on 2023-06-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20230616_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ky_song_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.kysong'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tj_song_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_set', to='song.tjsong'),
        ),
    ]
